spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
  gateway:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080


