spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: Xyna2604
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      show-sql: true
    datasource.hikari.maximum-pool-size: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8089

